home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

platform_users/urls.py
from django.urls import path

from platform_users import views

app_name = 'platform_users'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard_view'),
    path('update/<int:id>/', views.update_view, name='update_view'),
    path('update/create/<int:id>/', views.update_create_view, name='update_create_view'),
    path('delete/<int:id>/', views.delete_view, name='delete_view'),
    path('delete/confirm/<int:id>/', views.delete_confirm_view, name='delete_confirm_view'),
    path('register/', views.register_task_view, name='register_task_view'),
    path('register/task_create/', views.register_task_create, name='register_task_create'),
]

to_do/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('platform_users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

platform_users/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=30)
    desc = models.TextField(verbose_name='Description', blank=True)
    is_published = models.BooleanField(default=False, blank=True)
    is_finished = models.BooleanField(default=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')

    def __str__(self):
        return self.title

platform_users/forms/form_task.py
from django import forms
from platform_users.models import Task


class TaskForm(forms.ModelForm):

    title = forms.CharField(
        label='TITULO',
        error_messages= {
            'required': 'The title is required',
            'max_length': 'The text is too longer',
        },
        max_length=50,
    )
    desc = forms.CharField(
        label='DESCRICAO',
        widget=forms.Textarea(),
        required=False,
    )

    is_published = forms.BooleanField(
        label='TAREFA PUBLICA',
        required=False,
    )

    is_finished = forms.BooleanField(
        label='TAREFA FINALIZADA',
        required=False,
    )

    class Meta:
        model = Task
        fields = ['title', 'desc', 'is_published', 'is_finished']

platform_users/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from platform_users.models import Task

from .forms.form_task import TaskForm


# Create your views here.
@login_required(login_url='accounts:login_view')
def dashboard(request):
    user = request.user
    
    tasks = Task.objects.filter(user=user)
    limits = ['5', '8', '10']

    limit = request.GET.get('limit', '5')
    if not limit in limits:
        limit = limits[0]

    paginator = Paginator(tasks, limit)

    page_number = request.GET.get('page', '1')
    
    page_obj = paginator.get_page(page_number)
    
    
    return render(request, 'platform_users/dashboard.html', {
        'tasks': page_obj,
        'quantity_per_page': limits,
        'limit': limit,
        })

@login_required(login_url='accounts:login_view')
def update_view(request, id):
    task = get_object_or_404(Task, id=id, user=request.user)

    data = {
        'title': task.title,
        'desc': task.desc,
        'is_published': task.is_published,
        'is_finished': task.is_finished,
    }
    form = TaskForm(data)
    return render(request, 'platform_users/update.html', {'form': form, 'id':id})


@login_required(login_url='accounts:login_view')
def update_create_view(request, id):
    if request.method != 'POST':
        raise Http404()
    
    task = Task.objects.get(id=id)
    form = TaskForm(request.POST, instance=task)
    
    if form.is_valid():
        form.save()
        return redirect(reverse('platform_users:dashboard_view'))

    return redirect(reverse('platform_users:update_view', kwargs={'id':id}))

@login_required(login_url='accounts:login_view')
def delete_view(request, id):
    task = get_object_or_404(Task, id=id, user=request.user)
    return render(request, 'platform_users/delete.html', {'task':task})

@login_required(login_url='accounts:login_view')
def delete_confirm_view(request, id):
    if request.method != 'POST':
        raise Http404()

    task = Task.objects.get(id=id)
    task.delete()
    return redirect(reverse('platform_users:dashboard_view'))

@login_required(login_url='accounts:login_view')
def register_task_view(request):
    data = request.session.get('register_task_create')
    form = TaskForm(data)
    return render(request, 'platform_users/register_task.html', {'form':form})

@login_required(login_url='accounts:login_view')
def register_task_create(request):
    if request.method != 'POST':
        raise Http404()

    POST = request.POST
    request.session['register_task_create'] = POST
    
    form = TaskForm(POST)
    if form.is_valid():
        form_with_user = form.save(commit=False)
        form_with_user.user = request.user
        form_with_user.save()
        del(request.session['register_task_create'])
        return redirect(reverse('platform_users:dashboard_view'))
    
    return redirect(reverse('platform_users:register_task_view'))
    

platform_users/templates/platform_users/dashboard.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'title' %}
Dashboard
{% endblock 'title' %}
{% block 'content' %}
<section>
    <div class="container">
        <header class="header-title-dashboard">
            <h1>USUARIO: {{ request.user.first_name }}</h1>
            <h2><a href="{% url 'platform_users:register_task_view' %}">Adicionar Tarefa</a></h2>
        </header>
    
        <div class="tasks">
            <table class="public-tasks">
                <thead>
                    <tr>
                        <th>Titulo da tarefa</th>
                        <th>Data e hora criada</th>
                        <th>Data e hora atualizada</th>
                        <th>Editar</th>
                        <th>Deletar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr>
                        <td>{{ task.title }}</td>
                        <td>{{ task.created_at }}</td>
                        <td>{{ task.updated_at }}</td>
                        <td>
                            <div class="perfil-user update-task">
                                <a href="{% url 'platform_users:update_view' task.id %}">Editar</a>
                            </div>
                        </td>
                        <td>
                            <div class="perfil-user delete-task">
                                <a href="{% url 'platform_users:delete_view' task.id %}">Apagar</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="content-options">
            <div class="pagination">
                {% if tasks.paginator.num_pages > 1 %}
                    {% if tasks.has_previous %}
                        <a href="{% url 'platform_users:dashboard_view' %}?limit={{ tasks.paginator.per_page }}&page={{ tasks.previous_page_number }}">{{ tasks.previous_page_number }}</a>
                    {% endif %}

                    <span>{{ tasks.number }}</span>

                    {% if tasks.has_next %}
                        <a href="{% url 'platform_users:dashboard_view' %}?limit={{ tasks.paginator.per_page }}&page={{ tasks.next_page_number }}"> {{tasks.next_page_number }}</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="limit">
                <p>LIMITE POR PAGINA:</p>
                {% for quantity in quantity_per_page %}
                    {% if quantity == limit %}
                        <span>{{quantity}}</span>
                    {% else %}
                        <a href="{% url 'platform_users:dashboard_view' %}?limit={{quantity}}">{{ quantity }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>


{% endblock 'content' %}

platform_users/templates/platform_users/delete.html
{% extends 'global/base.html' %}
{% load static %}

{% block 'title' %}Apagar{% endblock 'title' %}
{% block 'content' %}
<section>
    <div class="container">
        <h2>Você tem certeza que quer excluir essa tarefa?</h2>
        <p>Titulo da tarefa: {{task.title}}</p>
        <a href="{% url 'platform_users:dashboard_view' %}">CANCELAR</a>
        <form action="{% url 'platform_users:delete_confirm_view' id=task.id %}" method="post">
            {% csrf_token %}
            <button type="submit">APAGAR</button>
        </form>
    </div>
</section>
{% endblock 'content' %}

platform_users/templates/platform_users/register_task.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'title' %}Registrar{% endblock 'title' %}
{% block 'content' %}
<section>
    <div class="container">
        <div class="form-container">
            <div class="img-content">
                <img src="{% static 'platform_users/img/register.svg' %}" alt="To do list">
            </div>
            <div class="form-content">
                <h2>REGISTRAR</h2>
                <form action="{% url 'platform_users:register_task_create' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="inputs">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    </div>
                    
                    {% endfor %}
                    <div class="inputs">
                        <button type="submit">REGISTRAR</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock 'content' %}

platform_users/templates/platform_users/update.html
{% extends 'global/base.html' %}
{% load static %}

{% block 'title' %}Atualizar{% endblock 'title' %}

{% block 'content' %}
<section>
    <div class="container">
        <div class="form-container">
            <div class="img-content">
                <img src="{% static 'platform_users/img/edit.svg' %}" alt="update form">
            </div>
            <div class="form-content">
                <h2>ATUALIZAR TAREFA</h2>
                <form action="{% url 'platform_users:update_create_view' id=id %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="inputs">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    </div>
                    
                    {% endfor %}
                    <div class="inputs">
                        <button type="submit">ATUALIZAR</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock 'content' %}