accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('login/auth/', views.login_auth_view, name='login_auth_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('register/create/', views.register_create_view, name='register_create_view'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

platform_users/urls.py
from django.urls import path

from platform_users import views

app_name = 'platform_users'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard_view'),
    path('update/<int:id>/', views.update_view, name='update_view'),
    path('update/create/<int:id>/', views.update_create_view, name='update_create_view'),
    path('delete/<int:id>/', views.delete_view, name='delete_view'),
    path('delete/confirm/<int:id>/', views.delete_confirm_view, name='delete_confirm_view'),
    path('register/', views.register_task_view, name='register_task_view'),
    path('register/task_create/', views.register_task_create, name='register_task_create'),
]

to_do/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('platform_users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/global/partials/footer.html
<footer>
    <div class="container">
        <div class="footer-content">
            <h1>Feito por <a href="https://github.com/walexhenrique">Walex Henrique</a></h1>
        </div>
    </div>
</footer>

templates/global/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'global/css/styles.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dangrek&display=swap" rel="stylesheet">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

templates/global/partials/header.html
<header>
    <div class="container">
        <nav>
            <ul class="content-ul">
                <div class="division">
                    <li class="li-item"><a href="{% url 'home:home' %}">TAREFAS</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="li-item"><a href="{% url 'platform_users:dashboard_view' %}">PAINEL</a></li>
                    {% endif %}
                </div>
                <div class="division">
                    {% if request.user.is_authenticated %}
                    <li class="li-item"><a href="{% url 'accounts:logout_view' %}">SAIR</a></li>
                    {% else %}
                    <li class="li-item"><a href="{% url 'accounts:login_view' %}">Logar</a></li>
                    <li class="li-item"><a href="{% url 'accounts:register_view' %}">Cadastrar</a></li>
                    {% endif %}
                </div>
            </ul>
        </nav>
    </div>
</header>