accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('login/auth/', views.login_auth_view, name='login_auth_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('register/create/', views.register_create_view, name='register_create_view'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

to_do/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('platform_users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/forms/login_form.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label='NOME DE USUARIO')
    password = forms.CharField(widget=forms.PasswordInput(), label='SENHA')

accounts/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class RegisterForm(forms.ModelForm):

    username = forms.CharField(
        label='NOME DE USUARIO',
        error_messages= {
            'required': 'Error, username is required',
            'max_length': 'USERNAME is very long',
        },
        max_length=150,
    )

    first_name = forms.CharField(
        label='PRIMEIRO NOME',
        error_messages={
            'required': 'Error, First name is required',
            'max_length': 'First name is very long',
        },
        max_length=150,
    )

    last_name = forms.CharField(
        label='SOBRENOME',
        error_messages={
            'required': 'Error, Last name is required',
            'max_length': 'Last name is very long',
        },
        max_length=150,
    )

    email = forms.EmailField(
        label='EMAIL',
        error_messages={
            'required':'Error, Email is required',
        },
    )

    password = forms.CharField(
        label='SENHA',
        widget=forms.PasswordInput(),
        error_messages={
            'required': 'Error, Password is required',
        }
    )

    password2 = forms.CharField(
        label='REPITA A SUA SENHA',
        widget=forms.PasswordInput(),
        error_messages={
            'required': 'Error, Please repeat your password',
        },
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


    def clean_username(self):
        username = self.cleaned_data.get('username', '')

        username_exists = User.objects.filter(username=username).exists()

        if username_exists:
            raise ValidationError('Username alredy exists in database', code='invalid')
        
        return username
    
    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        
        email_exists = User.objects.filter(email=email).exists()

        if email_exists:
            raise ValidationError('Email alredy exists in database', code='invalid')
        
        return email
    
    def clean_password(self):
        password = self.cleaned_data.get('password', '')

        if len(password) < 4:
            raise ValidationError('Error, Password is too short', code='invalid')
        
        return password
    
    def clean_password2(self):
        password2 = self.cleaned_data.get('password2', '')

        if len(password2) < 4:
            raise ValidationError('Error, Password is too short', code='invalid')
        
        return password2
    
    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password', '')
        password2 = cleaned_data.get('password2', '')

        if password != password2:
            raise ValidationError('Error, Passwords not equals', code='invalid')

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from accounts.forms.login_form import LoginForm
from accounts.forms.register_form import RegisterForm


# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('platform_users:dashboard_view'))
        
    form = LoginForm()
    return render(request, 'accounts/login.html', {'form':form})

def login_auth_view(request):
    if request.method != 'POST':
        raise Http404()

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = authenticate(request, username=username, password=password)

    if user:
        login(request, user)
        return redirect(reverse('platform_users:dashboard_view'))

    
    return redirect(reverse('accounts:login_view'))

def logout_view(request):
    logout(request)
    return redirect(reverse('accounts:login_view'))


def register_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('platform_users:dashboard_view'))

    register_data = request.session.get('register_form_data')

    form = RegisterForm(register_data)
    return render(request, 'accounts/register.html', {'form': form})

def register_create_view(request):
    if request.method != 'POST':
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST

    form = RegisterForm(POST)
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()

        del(request.session['register_form_data'])
        return redirect(reverse('accounts:login_view'))
    
    return redirect(reverse('accounts:register_view'))

accounts/templates/accounts/index.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'content' %}
<section>
    <div class="container">
        <header class="header-title">
            <h1>NOVAS TAREFAS PUBLICADAS</h1>
        </header>
    
    <div class="tasks">
        <table class="public-tasks">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Titulo da tarefa</th>
                    <th>Data e hora</th>
                    <th>Visualizar perfil</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>RAIMUNDO</td>
                    <td>FAZER CHURROS</td>
                    <td>22-10-2022 19:00:20</td>
                    <td>
                        <div class="perfil-user">
                            <a href="#">PERFIL</a>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>RAIMUNDO</td>
                    <td>FAZER CHURROS</td>
                    <td>22-10-2022 19:00:20</td>
                    <td>
                        <div class="perfil-user">
                            <a href="#">PERFIL</a>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>RAIMUNDO</td>
                    <td>FAZER CHURROS</td>
                    <td>22-10-2022 19:00:20</td>
                    <td>
                        <div class="perfil-user">
                            <a href="#">PERFIL</a>
                        </div>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>
</div>
</section>
{% endblock 'content' %}

accounts/templates/accounts/login.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'title' %} Logar {% endblock 'title' %}

{% block 'content' %}
<section>
    <div class="container">
        <div class="form-container">
            <div class="img-content">
                <img src="{% static '/accounts/img/to_do.svg'%}" alt="To do list">
            </div>
            <div class="form-content">
                <h2>LOGIN</h2>
                <form action="{% url 'accounts:login_auth_view' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="inputs">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    </div>
                    {% endfor %}
                    <div class="inputs">
                        <button type="submit">LOGAR</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock 'content' %}

accounts/templates/accounts/register.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'title' %}Registrar{% endblock 'title' %}
{% block 'content' %}
<section>
    <div class="container">
        <div class="form-container">
            <div class="img-content">
                <img src="{% static 'accounts/img/auth.svg' %}" alt="To do list">
            </div>
            <div class="form-content">
                <h2>REGISTRAR</h2>
                <form action="{% url 'accounts:register_create_view' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="inputs">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    </div>
                    
                    {% endfor %}
                    <div class="inputs">
                        <button type="submit">REGISTRAR</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock 'content' %}